# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Z_AaxxT4ahG_1T2EfKyJsH0gt91FEk6m
"""


import os
import time
import streamlit as st
from pypdf import PdfReader
from sentence_transformers import SentenceTransformer
import faiss
from openai import OpenAI

st.set_page_config(
    page_title="Healthcare RAG Assistant",
    page_icon="🩺",
    layout="centered"
)

st.title("🩺 Healthcare RAG Assistant")
st.caption("Ask questions about Acne, Eczema, Psoriasis, Skin Cancer, and UV Radiation.")

DEEPSEEK_API_KEY = st.secrets["DEEPSEEK_API_KEY"]

client = OpenAI(
    api_key=DEEPSEEK_API_KEY,
    base_url="https://api.deepseek.com"
)

@st.cache_resource
def build_knowledge_base():
    pdf_files = [f for f in os.listdir() if f.endswith(".pdf")]

    if not pdf_files:
        st.error("No PDF files found. Please upload PDF files in the same folder as app.py.")
        st.stop()

    progress = st.progress(0, text=" Reading PDF files...")
    documents = []

    for pdf_file in pdf_files:
        reader = PdfReader(pdf_file)
        for page_number, page in enumerate(reader.pages):
            text = page.extract_text()
            if text and text.strip():
                documents.append({
                    "text": text,
                    "source": pdf_file,
                    "page": page_number + 1
                })

    progress.progress(30, text=" Splitting text into chunks...")

    def split_text(text, chunk_size=800, overlap=150):
        chunks = []
        start = 0
        while start < len(text):
            end = start + chunk_size
            chunk = text[start:end]
            if chunk.strip():
                chunks.append(chunk)
            start = end - overlap
        return chunks

    chunks = []
    for doc in documents:
        for chunk in split_text(doc["text"]):
            chunks.append({
                "text": chunk,
                "source": doc["source"],
                "page": doc["page"]
            })

    if not chunks:
        st.error("PDF files were found, but no readable text was extracted.")
        st.stop()

    progress.progress(60, text=" Loading embedding model...")
    embedding_model = SentenceTransformer("sentence-transformers/all-MiniLM-L6-v2")

    progress.progress(80, text=" Building search index...")
    texts = [chunk["text"] for chunk in chunks]

    embeddings = embedding_model.encode(
        texts,
        convert_to_numpy=True,
        show_progress_bar=True
    )

    embeddings = embeddings.astype("float32")
    faiss.normalize_L2(embeddings)

    dimension = embeddings.shape[1]
    index = faiss.IndexFlatL2(dimension)
    index.add(embeddings)

    progress.progress(100, text=" Ready!")
    time.sleep(0.5)
    progress.empty()

    return chunks, embedding_model, index


chunks, embedding_model, index = build_knowledge_base()

def retrieve_chunks(question, top_k=5):
    question_embedding = embedding_model.encode(
        [question],
        convert_to_numpy=True
    ).astype("float32")

    faiss.normalize_L2(question_embedding)

    distances, indices = index.search(question_embedding, top_k)
  
    results = []
    for idx in indices[0]:
        results.append(chunks[idx])

    return results

def generate_answer(question, retrieved_chunks):
    context = "\n\n---\n\n".join([
        f"Source: {chunk['source']}, Page: {chunk['page']}\n{chunk['text'][:1200]}"
        for chunk in retrieved_chunks
    ])

    prompt = f"""
You are a healthcare information assistant.

Use the provided context to answer the question as accurately as possible.
If the context contains related information, summarize it clearly.
Only say:
"I could not find enough information in the provided documents."
if the context is completely unrelated or empty.

Rules:
- Do not diagnose the user.
- Do not replace professional medical advice.
- Keep the answer clear and concise.
- Do not include unrelated information.

Context:
{context}

Question:
{question}

Answer:
"""

    response = client.chat.completions.create(
        model="deepseek-chat",
        messages=[
            {"role": "user", "content": prompt}
        ],
        max_tokens=500,
        temperature=0.0
    )

    return response.choices[0].message.content

with st.sidebar:
    st.header("Available Topics")
    st.write(" Acne")
    st.write(" Eczema")
    st.write(" Psoriasis")
    st.write("Skin Cancer")
    st.info(
        "This assistant provides educational information only "
        "and does not replace professional medical advice."
    )

if "messages" not in st.session_state:
    st.session_state.messages = [
        {
            "role": "assistant",
            "content": "Hello! Ask me a healthcare question based on the uploaded documents."
        }
    ]

for message in st.session_state.messages:
    with st.chat_message(message["role"]):
        st.write(message["content"])

question = st.chat_input("Type your question here...")

if question:
    st.session_state.messages.append({
        "role": "user",
        "content": question
    })

    with st.chat_message("user"):
        st.write(question)

    with st.chat_message("assistant"):
        with st.spinner("Retrieving documents and generating answer using DeepSeek..."):
            retrieved_chunks = retrieve_chunks(question, top_k=5)
            answer = generate_answer(question, retrieved_chunks)

            st.write(answer)

            with st.expander("Retrieved Sources"):
                for chunk in retrieved_chunks:
                    st.write(f"- {chunk['source']} page {chunk['page']}")

    st.session_state.messages.append({
        "role": "assistant",
        "content": answer
    })
